# netlify.toml (na raiz do seu repositório Git)

[build]
  command = "npm run build" # MUDADO de bun run build para npm run build
  publish = ".next"

[context.production.environment]
  NODE_VERSION = "20" # ou "18", mantenha o que você já usou
  NEXT_CACHE_PATH = ""