# netlify.toml (na raiz do seu repositório Git)

[build]
  command = "bun run build" # Mantenha o bun por enquanto, vamos testar isso depois
  publish = "sandbox/.next" # Caminho relativo à raiz do repositório
  base = "sandbox" # A pasta onde seu projeto Next.js está

[context.production.environment]
  # Forçar uma versão específica do Node.js
  # O Next.js 15.3.5 geralmente funciona bem com Node.js 18 ou 20.
  # Você pode verificar qual versão está usando localmente com `node -v` e tentar a mesma.
  NODE_VERSION = "20" # ou "18" se preferir uma versão mais estável/comum

  # Desativar o cache do Next.js para este build (apenas para teste)
  # Isso força um build limpo sem usar nenhum cache prévio que possa estar corrompido
  NEXT_CACHE_PATH = ""